#! /bin/sh

LOGFILE="$XDG_STATE_HOME/sway-session"

exec > $LOGFILE 2>&1

set -x echo "Starting sway at $( date )"

export XDG_SESSION_TYPE=wayland

export MOZ_ENABLE_WAYLAND=1
export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1
export QT_QPA_PLATFORM=wayland-egl
export QT_WAYLAND_FORCE_DPI=physical
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1

exec sway
